# Databricks App Configuration
# This file configures the Koop Databricks Provider app

# App resources - General-purpose cluster for querying geospatial data
# Note: Using general-purpose cluster instead of SQL warehouse
# resources:
#   - name: databricks-cluster
#     description: General-purpose cluster for Koop provider queries
#     cluster:
#       id: YOUR_CLUSTER_ID

# Environment variables for the app
env:
  - name: DATABRICKS_SERVER_HOSTNAME
    value: your-workspace.cloud.databricks.com
  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/YOUR_WAREHOUSE_ID
    # Or for general-purpose cluster:
    # value: sql/protocolv1/o/YOUR_ORG_ID/YOUR_CLUSTER_ID
  - name: DATABRICKS_TOKEN
    value: YOUR_DATABRICKS_TOKEN
  - name: LOG_LEVEL
    value: INFO
  - name: SERVE_DEMO_PAGES
    value: "true"
  # Note: PORT is automatically set to 8000 by Databricks Apps platform

# RECOMMENDED: For production, use secrets instead of hardcoding tokens:
# env:
#   - name: DATABRICKS_TOKEN
#     secret:
#       scope: your-secret-scope
#       key: databricks-token
#
# See: https://docs.databricks.com/en/security/secrets/index.html

# Compute configuration
compute:
  size: small

# Optional: Auto-scaling configuration
# scale:
#   min_instances: 1
#   max_instances: 3

# Authentication configuration
# For public access without OAuth, you need to deploy outside of Databricks Apps
# (e.g., standalone Docker, AWS ECS, Azure Container Instances)
# Databricks Apps always require workspace authentication
authentication:
  required: false  # Still requires OAuth login in Databricks Apps
